Sprint_3
chris-lebedeva/Sprint_3 pull request #1
Opened 2023-05-27 18:13 UTC by chris-lebedeva

2023-05-28 21:37 UTC, kadirovgm requested changes

2023-05-28 21:37 UTC, kadirovgm commented on README.md
> +
Отлично! очень хорошее readme

2023-05-28 21:37 UTC, kadirovgm commented on conftest.py
> +def driver():
отлично!

2023-05-28 21:37 UTC, kadirovgm commented on conftest.py
> +    driver.maximize_window()
Можно также сюда выносить открытие главной страницы, но это не обязательно, если все твои тесты не начинаются с главной

2023-05-28 21:37 UTC, kadirovgm commented on data.py
> +class Data:
Супер, молодец, что вынес тестовые данные отдельно

Это нужно для легкой поддержке проекта и переиспользовании тестовых данных, мы должны стремиться к тому, чтобы разделять код и тестовые данные, тем самым избегая повторений

2023-05-28 21:37 UTC, kadirovgm commented on requirements.txt
> +PyAutoGUI==0.9.54
интересное решение

2023-05-28 21:37 UTC, kadirovgm commented on urls.py
> +class Urls:
четко :)

2023-05-28 21:37 UTC, kadirovgm commented on tests/test_constructor_page.py
> +    time.sleep(1)
нужно исправить: немножко не понял, зачем здесь sleep()? если пользуешься явным ожиданием, то использование speep() - плохое решение, лучше всегда пользоваться WebDriverWait в комбинации с ExpectedCondition

пример
```
element = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.ID, "myDynamicElement"))
    )
```

ps. актуально для всех тестов ниже

2023-05-28 21:37 UTC, kadirovgm commented on tests/test_constructor_page.py
> +    time.sleep(1)
Нужно исправить: надо конкретно избавляться от привычки использовать sleep() - когда тестов станет стони, это будет +100 сек к прогону тестов, что довольно долго, учитывая что это не время прогона, а время простоя

2023-05-29 18:36 UTC, chris-lebedeva commented on tests/test_constructor_page.py
> +    time.sleep(1)
Привет, Рушат! :) 
Я убрала time.sleep() везде, где это было возможно. В тестах переключения между разделами я добавила его просто для наглядности, чтобы во время прохода было видно визуально, что раздел сменился)
А вот в тесте создания заказа никак, к сожалению, не удалось избавиться от sleep(), потому что тогда drag&drop не отрабатывал. Я перепробовала разные варианты из expected_conditions, но ни один не помог. Поэтому в обновлённом пуллреквесте я постаралась оптимизировать время прохода.
Ну и ещё подправила readme, потому что затесалось нижнее подчёркивание в заголовок.
Из-за того, что правки небольшие не стала из разделять на отдельные коммиты. Надеюсь, всё ок :)

2023-05-29 21:18 UTC, kadirovgm commented on tests/test_constructor_page.py
> +    time.sleep(1)
Привет! да, в частных случаях, если обходных путей нет, то можно оставить, у тебя из было много, поэтому обратил внимание, ими можно пользоваться при отладке тестов, но в общую ветку уже пушить без них, чтобы стремиться к ускорению прогона тестов :)

2023-05-29 21:18 UTC, kadirovgm approved these changes

2023-05-30 18:21 UTC, merged